### PR TITLE
Add arm64-osx-dynamic triplet to continuous integration to support Apple Silicon platforms (M1, M2, M3 etc)

### PR DESCRIPTION
**Pull request by as-ascii**

### CODE REVIEW

**Comment by kgantchev** [comment]
My name is Kiril Gantchev, I'm the CEO and co-founder of [FlyCI](https://flyci.net). Thanks for giving FlyCI a try. I hope you enjoy it and please feel free to reach out should you have any issues. We're still in the public Beta phase, so we're trying to iron out any issues that happen in the process. We appreciate your support!

Best Regards,
Kiril Gantchev

Discord: [FlyCI](https://discord.gg/JyCjh439da) | Twitter: [flyciapp](https://twitter.com/flyciapp) | LinkedIn: [FlyCI](https://linkedin.com/company/flyci)

**Comment by as-ascii** [comment]
> My name is Kiril Gantchev, I'm the CEO and co-founder of [FlyCI](https://flyci.net). Thanks for giving FlyCI a try. I hope you enjoy it and please feel free to reach out should you have any issues. We're still in the public Beta phase, so we're trying to iron out any issues that happen in the process. We appreciate your support!
> 
> Best Regards, Kiril Gantchev
> 
> Discord: [FlyCI](https://discord.gg/JyCjh439da) | Twitter: [flyciapp](https://twitter.com/flyciapp) | LinkedIn: [FlyCI](https://linkedin.com/company/flyci)

We appreciate your help with the DocWire SDK project. We will contact you soon.

**Comment by kgantchev** [comment]
Hi @as-ascii, 

We would be very thankful if you share a few words about your experience with FlyCI. We would love to add your story to our case studies.

**Comment by Novitzmann** [comment]
Hi Kiril.  We've been using FlyCI to make our MacOS development process better. Here's what we've done:
* Added architecture detection to automatically adjust build settings for OSX, ensuring optimal performance.
* Fixed issues with sanitizers in our GitHub CI for the arm64-osx-dynamic configuration, improving code quality.
* Corrected syntax errors in our build scripts, streamlining our builds.
* Improved logging for template symbols, making debug logs clearer.
* Brought sanitizers back into our arm64-osx-dynamic CI, reinforcing our commitment to secure and reliable code.
* Updated our documentation to include the arm64-osx-dynamic configuration, keeping our information up to date.
FlyCI has been key in speeding up these tasks and supporting our complex CI/CD needs, especially with the latest MacOS architectures. If you need more details for the case study, just let us know.

**Comment by as-ascii** [comment]
@coderabbitai review

**Comment by as-ascii** [comment]
@coderabbitai review

**Comment by as-ascii** [comment]
@coderabbitai review

**Comment by as-ascii** [comment]
@coderabbitai review

**Pull request merged**
